---------------------------------------------------------------
--  
-- SCHEMA:  STG
-- NAME:    STG_F_BHATBHATENI_SLS_TRXN_B
--
---------------------------------------------------------------
CREATE
OR REPLACE TABLE stg.STG_F_BHATBHATENI_SLS_TRXN_B (
    ID INT NOT NULL PRIMARY KEY,
    STORE_ID INT FOREIGN KEY REFERENCES STG_D_STORE_LU (ID),
    PRODUCT_ID INT FOREIGN KEY REFERENCES STG_D_PRODUCT_LU (ID),
    CUSTOMER_ID INT FOREIGN KEY REFERENCES STG_D_CUSTOMER_LU (ID),
    TRANSACTION_TIME TIMESTAMP_NTZ,
    QUANTITY NUMBER (38, 0),
    AMOUNT NUMBER (20, 2),
    DISCOUNT NUMBER (20, 2)
);


---------------------------------------------------------------
--  
-- SCHEMA:  TMP
-- NAME:    TMP_F_BHATBHATENI_SLS_TRXN_B
--
---------------------------------------------------------------
CREATE
OR REPLACE TABLE tmp.TMP_F_BHATBHATENI_SLS_TRXN_B (
    ID INT NOT NULL PRIMARY KEY,
    STORE_ID INT FOREIGN KEY REFERENCES TMP_D_STORE_LU (ID),
    PRODUCT_ID INT FOREIGN KEY REFERENCES TMP_D_PRODUCT_LU (ID),
    CUSTOMER_ID INT FOREIGN KEY REFERENCES TMP_D_CUSTOMER_LU (ID),
    TRANSACTION_TIME TIMESTAMP_NTZ (9),
    QUANTITY NUMBER (38, 0),
    AMOUNT NUMBER (20, 2),
    DISCOUNT NUMBER (20, 2)
);


---------------------------------------------------------------
--  
-- SCHEMA:  DWH
-- NAME:    DWH_F_BHATBHATENI_SLS_TRXN_B
--
---------------------------------------------------------------
CREATE
OR REPLACE TABLE dwh.DWH_F_BHATBHATENI_SLS_TRXN_B (
    SALES_TXN_ID INT NOT NULL PRIMARY KEY,
    --
    STORE_KY INT FOREIGN KEY REFERENCES DWH_D_STORE_LU (STORE_KY),
    STORE_ID INT FOREIGN KEY REFERENCES DWH_D_STORE_LU (STORE_ID),
    PRODUCT_KY INT FOREIGN KEY REFERENCES DWH_D_PRODUCT_LU (PRODUCT_KY),
    PRODUCT_ID INT FOREIGN KEY REFERENCES DWH_D_PRODUCT_LU (PRODUCT_ID),
    CUSTOMER_KY INT FOREIGN KEY REFERENCES DWH_D_CUSTOMER_LU (CUSTOMER_KY),
    CUSTOMER_ID INT FOREIGN KEY REFERENCES DWH_D_CUSTOMER_LU (CUSTOMER_ID),
    --
    DAY_KY VARCHAR,
    -- 
    TRANSACTION_TIME TIMESTAMP_NTZ (9),
    QUANTITY NUMBER (38, 0),
    AMOUNT NUMBER (20, 2),
    DISCOUNT NUMBER (20, 2),
    NET_AMOUNT NUMBER (20, 2),
    -- 
    INSERTED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);